feat: #14 add-bookings
Indiannka/java-shareit pull request #2
Opened 2022-09-12 22:34 UTC by Indiannka

14 спринт

2022-09-14 08:32 UTC, makholin commented
В коммиты лучше писать сообщения с информацией, что было сделано
Вот например, как выглядят сообщения коммитов в самом спринге: https://github.com/spring-projects/spring-framework/commits/main

2022-09-14 08:56 UTC, makholin commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +    private static final String USER_ID_HEADER = "X-Sharer-User-Id";
константы должны быть первыми в списке полей и отделены пустой строкой от других полей

2022-09-14 08:58 UTC, makholin commented on src/main/java/ru/practicum/shareit/booking/converter/IncomingBookingDTOToBooking.java
> +    public Booking convert(IncomingBookingDto bookingDTO) {
название переменной должно быть в camelCase
`bookingDto`

2022-09-14 08:59 UTC, makholin commented on src/main/java/ru/practicum/shareit/booking/BookingRepository.java
> +    Optional<Booking> findFirstByBooker_IdAndItem_IdAndStartIsBefore(Long bookerId, Long itemId, LocalDateTime dateTime);
в названиях методов не должно быть нижнего подчеркивания, формат должен быть camelCase
тем более, что jpa поддерживает такой формат

2022-09-14 09:01 UTC, makholin commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImp.java
> +    private static final int OWNER = 1;
константы должны быть первыми в списке полей

2022-09-14 09:01 UTC, makholin commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImp.java
> +    private int getUserType(Booking booking, Long userId) {
для типа юзера надо сделать отдельный enum, а не использовать цифры

2022-09-14 09:03 UTC, makholin commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImp.java
> +        assert booking != null;
использовать ассерты не стоит в коде, потому что приложение может быть запущенно без флага `-ea` и тогда этот ассерт просто не сработает

нужно использовать if и бросать исключение с осмысленным месседжем в нем

2022-09-14 09:05 UTC, makholin commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImp.java
> +        if (Boolean.TRUE.equals(approval)) {
можно сделать аргумент метода сделать примитивом и тогда не нужно будет такой конструкции в условии
можно будет сделать так
```
booking.setStatus(approval ? APPROVED : REJECTED)
save(booking)
```

2022-09-14 09:09 UTC, makholin commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImp.java
> +        if (Arrays.stream(State.values()).map(Enum::name).noneMatch(s -> s.equals(state))) {
лучше сделать отдельный метод, который будет парсить из строки

```
private State parseState(String value) {
 return State.valueOf(value);
 }
```

если нужно бросить StateValidationEx, то эту конструкцию в методе можно обернуть в try catch и в catch перехватывать IllegalArgEx и бросать свое

2022-09-14 09:09 UTC, makholin commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImp.java
> +        Boolean isAvailable = item.getAvailable();
тоже стоит сделать поле примитивом

2022-09-14 09:12 UTC, makholin commented on src/main/java/ru/practicum/shareit/booking/converter/BookingToIncomingBookingDto.java
> +public class BookingToIncomingBookingDto implements Converter<Booking, IncomingBookingDto> {
нужно исправить название, это не является дто объектом
это маппер или конвертер
правильнее будет BookingMapper или BookingConverter

и нужно либо сделать его классом со статическими методами и не создавать объект класса
либо сделать бином спринга и чтобы объект создавался и инжектился спрингом

2022-09-14 09:12 UTC, makholin commented on src/main/java/ru/practicum/shareit/booking/converter/BookingToIncomingBookingDto.java
> +public class BookingToIncomingBookingDto implements Converter<Booking, IncomingBookingDto> {
общий интерфейс тут тоже не решает никакой проблемы, его можно удалить

2022-09-14 09:15 UTC, makholin commented on src/main/java/ru/practicum/shareit/item/dto/CommentDTO.java
> +public class CommentDTO {
название класса должно быть в CamelCase
`CommentDto`

2022-09-14 09:15 UTC, makholin commented on src/main/java/ru/practicum/shareit/item/dto/ItemWithBookings.java
> +
достаточно одной пустой строки

2022-09-14 09:16 UTC, makholin requested changes
Нужно исправить замечания

2022-09-17 10:05 UTC, Indiannka commented on src/main/java/ru/practicum/shareit/booking/converter/BookingToIncomingBookingDto.java
> +public class BookingToIncomingBookingDto implements Converter<Booking, IncomingBookingDto> {
Переделала, только не понимаю чем плох ConversionService )

2022-09-17 10:07 UTC, Indiannka commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImp.java
> +        assert booking != null;
Спасибо, учту. А что за флаг -ea? Еще поищу инфу, сходу не нашла, но подсказке буду признательна.

2022-09-19 13:01 UTC, TyutterinYakov reviewed
Добрый день! В целом - хорошо) Отметил то, что следует исправить и то, что можно сделать лучше) Хорошего дня! Если возникнут вопросы - пиши в слак, буду рад помочь)

2022-09-19 13:01 UTC, TyutterinYakov commented on src/main/java/ru/practicum/shareit/booking/Booking.java
>  @Data
Аннотация @Data не должна использоваться над сущностями, так как она включает в себя @EqualsAndHashCode, что может вызвать ошибку при вызове этих методов вне транзакции

2022-09-19 13:01 UTC, TyutterinYakov commented on src/main/java/ru/practicum/shareit/booking/BookingRepository.java
> +    Collection<Booking> findCurrentByBookerId(Long bookerId, LocalDateTime now);
Можно было бы оставить возможность выбора сортировки, чтобы в случае, когда нам потребуется другой порядок - не писать еще один метод) Для этого в аргументах метода следует так же ожидать Sort sort.
Объект этого класса создается подобным образом: Sort.by(Sort.Direction.DESC, "start");
А order by booking.start следовательно нужно будет убрать)
Аналогично и со всеми другими методами и запросами)
Например, вместо findByBookerIdOrderByStartDesc останется findByBookerId

2022-09-19 13:01 UTC, TyutterinYakov commented on src/main/java/ru/practicum/shareit/booking/dto/IncomingBookingDto.java
> +    @Future
В данном случае хорошо было бы использовать аннотацию @FutureOrPresent, так как время старта может быть равно текущему)

2022-09-19 13:01 UTC, TyutterinYakov commented on src/main/java/ru/practicum/shareit/item/Comment.java
> +@Data
Аналогично, аннотацию @data следует убрать

2022-09-19 13:01 UTC, TyutterinYakov commented on src/main/java/ru/practicum/shareit/item/ItemController.java
>                            @Validated({Update.class})
@Validated({Update.class}) следует разместить перед аннотацией @RequestBody

2022-09-19 13:01 UTC, TyutterinYakov commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    private final CommentToCommentDtoConverter commentToCommentDtoConverter;
Хорошо было бы все-таки выбрать, где производить преобразование к DTO, на уровне сервиса, либо же на уровне контроллера)

2022-09-19 13:01 UTC, TyutterinYakov commented on src/main/java/ru/practicum/shareit/user/converter/UserDtoToUserConverter.java
> +public class UserDtoToUserConverter {
Думаю, что создавать на каждый метод отдельный класс-конвертер не имеет смысла. Лучше для каждой сущности и связанными с ней ДТО создать один класс и разместить все методы в нем) Аналогично с другими подобными классами

2022-09-19 13:01 UTC, TyutterinYakov commented on src/main/java/ru/practicum/shareit/user/UserServiceImp.java
>  public class UserServiceImp implements UserService {
Хорошо было бы во всех сервисах работать с транзакциями. Для этого над классом достаточно навесить аннотацию @transactional(readOnly = true), таким образом мы укажем, что изменения в сущностях не будут фиксировать в БД, а для того, чтобы фиксация в некоторых методах происходила по завершению транзакции, достаточно над этим методом навесить @transactional
А так же, если возникнет непроверямое исключение, все изменения в пределах транзакции будут откатаны назад) Так же не нужно будет при обновлении вызывать save репозитория, если производится изменение полученной сущности, так как они будут зафиксированы после завершения транзакции)

2022-09-19 13:01 UTC, TyutterinYakov commented on src/main/java/ru/practicum/shareit/item/dto/CommentDto.java
> +    @NotBlank(message = "Поле text не должно быть пустым", groups = {Create.class})
Проверка на null входит в NotBlank, здесь аннотация @NotNull не требуется)

2022-09-19 13:01 UTC, TyutterinYakov commented on src/main/java/ru/practicum/shareit/item/ItemServiceImp.java
> +    private final UserService userService;
Если будешь работать с транзакциями, то лучше исключить внедрение сервисов в другие сервисы, так как при обращении к методу из другого сервиса будет создавать дополнительная транзакция, что не очень хорошо со стороны производительности

2022-09-19 13:01 UTC, TyutterinYakov commented on src/main/java/ru/practicum/shareit/item/ItemServiceImp.java
> +    private final CommentDtoToCommentConverter commentDtoToCommentConverter;
Следует создать общие конвертеры для разных групп) Более подробно написал в конвертере ниже)

2022-09-19 13:01 UTC, TyutterinYakov commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImp.java
> +        } catch (Exception exception) {
Следует обрабатывать только то исключение, которое мы ожидаем)

2022-09-19 13:01 UTC, TyutterinYakov commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImp.java
> +        } catch (Exception exception) {
Следует обрабатывать только то исключение, которое мы ожидаем)

2022-09-19 13:01 UTC, TyutterinYakov commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +                                             @RequestParam(defaultValue = "ALL", required = false) String state) {
Можно было бы принимать не String, а State, Spring за нас произведет преобразование, а при необходимости выбросит исключение) Таким образом мы избавимся от проверок в коде и от преобразований к State)

2022-09-19 13:01 UTC, TyutterinYakov commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +                                              @RequestParam(defaultValue = "ALL", required = false) String state) {
Можно было бы принимать не String, а State, Spring за нас произведет преобразование, а при необходимости выбросит исключение) Таким образом мы избавимся от проверок в коде и от преобразований к State)

2022-09-19 13:01 UTC, TyutterinYakov commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +                                     @Validated({Create.class})
Использовать следует либо @Validated либо @Valid)

2022-09-19 13:01 UTC, TyutterinYakov commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +@Validated
Аннотация @Calidated здесь не требуется, так как нет аргументов, которые требовалось бы валидировать с помощью дополнительных аннотаций валидации)

2022-09-19 18:47 UTC, Indiannka commented on src/main/java/ru/practicum/shareit/booking/BookingRepository.java
> +    Collection<Booking> findCurrentByBookerId(Long bookerId, LocalDateTime now);
+

2022-09-19 18:58 UTC, Indiannka commented on src/main/java/ru/practicum/shareit/booking/Booking.java
>  @Data
+
>>что может вызвать ошибку при вызове этих методов вне транзакции 
А можно поподробнее где-то почитать?

2022-09-19 18:59 UTC, Indiannka commented on src/main/java/ru/practicum/shareit/booking/dto/IncomingBookingDto.java
> +    @Future
+

2022-09-19 18:59 UTC, Indiannka commented on src/main/java/ru/practicum/shareit/item/Comment.java
> +@Data
+

2022-09-19 19:05 UTC, Indiannka commented on src/main/java/ru/practicum/shareit/item/ItemController.java
>                            @Validated({Update.class})
У меня так тесты падают

2022-09-19 19:28 UTC, Indiannka commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    private final CommentToCommentDtoConverter commentToCommentDtoConverter;
Так у меня вроде все в контроллере кроме ItemWithBookings, т.к. я не стала выносить методы по добавлению бронирований и комментариев в контроллер, а оставила в сервисе. Это критично?

2022-09-19 20:57 UTC, Indiannka commented on src/main/java/ru/practicum/shareit/user/UserServiceImp.java
>  public class UserServiceImp implements UserService {
>>Так же не нужно будет при обновлении вызывать save репозитория, если производится изменение полученной сущности, так как они будут зафиксированы после завершения транзакции)
Не совсем уловила суть. Это все в случае непроверяемого исключения?
суть транзакций понятна, но как правильно с ними работать еще не очень.. Надеюсь, все правильно сделала, спасибо)

2022-09-19 20:57 UTC, Indiannka commented on src/main/java/ru/practicum/shareit/user/UserServiceImp.java
>  public class UserServiceImp implements UserService {
Не совсем уловила суть. Это все в случае непроверяемого исключения?
суть транзакций понятна, но как правильно с ними работать еще не очень.. Надеюсь, все правильно сделала, спасибо)

2022-09-19 21:15 UTC, Indiannka commented on src/main/java/ru/practicum/shareit/user/converter/UserDtoToUserConverter.java
> +public class UserDtoToUserConverter {
переделала) хотя и CoversionService вроде норм был изначально)

2022-09-19 21:18 UTC, Indiannka commented on src/main/java/ru/practicum/shareit/item/dto/CommentDto.java
> +    @NotBlank(message = "Поле text не должно быть пустым", groups = {Create.class})
+

2022-09-19 21:18 UTC, Indiannka commented on src/main/java/ru/practicum/shareit/item/ItemServiceImp.java
> +    private final UserService userService;
+

2022-09-19 21:18 UTC, Indiannka commented on src/main/java/ru/practicum/shareit/item/ItemServiceImp.java
> +    private final CommentDtoToCommentConverter commentDtoToCommentConverter;
+

2022-09-19 22:12 UTC, Indiannka commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImp.java
> +        } catch (Exception exception) {
ExceptionHandler, который перехватывает у меня все исключения ловит его первым, если я пытаюсь поймать IllegalArgEx

2022-09-19 22:18 UTC, Indiannka commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImp.java
> +        } catch (Exception exception) {
ExceptionHAndler, который обрабатывает все прочие исключения ловит IllegalArgEx первым, поэтому я поставила просто EXception.

2022-09-19 22:18 UTC, Indiannka commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImp.java
> +        } catch (Exception exception) {
ExceptionHAndler, который обрабатывает все прочие исключения ловит IllegalArgEx первым, поэтому я поставила просто EXception.

2022-09-19 22:19 UTC, Indiannka commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +                                             @RequestParam(defaultValue = "ALL", required = false) String state) {
Не разобралась как перехватывать в таком случае  из контроллера валидацию State.

2022-09-19 22:30 UTC, Indiannka commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +                                     @Validated({Create.class})
@Validated({Create.class}) работает над проверкой null
@Valid над Future 
Без какой-либо падают тесты

2022-09-19 22:33 UTC, Indiannka commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +@Validated
без нее падает. Не срабатывает проверка RequestBody

2022-09-19 22:44 UTC, Indiannka commented on src/main/java/ru/practicum/shareit/booking/Booking.java
>  @Data
можно поподробнее, если требуется какое-то специфичное сравнение? Просто мне наоборот советовали ставить @Data в прошлых ревью

2022-09-20 13:21 UTC, TyutterinYakov commented on src/main/java/ru/practicum/shareit/user/converter/UserDtoToUserConverter.java
> +public class UserDtoToUserConverter {
Это не совсем удобно и добавляет слишком много шаблонного кода)

2022-09-20 13:23 UTC, TyutterinYakov commented on src/main/java/ru/practicum/shareit/user/UserServiceImp.java
>  public class UserServiceImp implements UserService {
Так как, скорее всего, просто не была переопределена @Transactional(readOnly = true) над методами, где требуется сохранить изменения)

2022-09-20 13:30 UTC, TyutterinYakov approved these changes
Добрый вечер! Поздравляю с успешной сдачей спринта :) Я отметил оставшиеся недочеты, но думаю, что ты справишься с ними вне ревью :) Но в следующий раз обязательно проверю) Хорошего вечера и отличного настроения🌉

2022-09-20 13:30 UTC, TyutterinYakov commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +                                     @Validated({Create.class})
Потому что не указана группа 
@FutureOrPresent(groups = Create.class)
@Future(groups = Create.class)
В любом случае выбрать стоит только одну аннотацию

2022-09-20 13:30 UTC, TyutterinYakov commented on src/main/java/ru/practicum/shareit/booking/dto/IncomingBookingDto.java
> +    @Future
не исправлено, так же следует указать группу

2022-09-20 13:30 UTC, TyutterinYakov commented on src/main/java/ru/practicum/shareit/booking/dto/IncomingBookingDto.java
> +    @Future
Следует указать группу

2022-09-20 14:23 UTC, Indiannka commented on src/main/java/ru/practicum/shareit/booking/dto/IncomingBookingDto.java
> +    @Future
аа, ну да... поправлю) Спасибо!!!

2022-10-11 11:56 UTC, merged